In [43]:
import numpy as np

In [44]:
print("Numpy version:",np.__version__)
print(f"Numpy Configuration: {np.show_config()}")

Numpy version: 2.5.1
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.33.112.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-gi283v49/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/i

c:\Users\Ayatullah\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [45]:
Null_vector=np.zeros(10,dtype=int)
Null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
arr=np.array([1,2,3,4])
print(arr.nbytes) # Equal arr.itemsize * arr.sizec

32


In [47]:
# Bash: python -m pydoc numpy.add This in cmd for documentation

In [48]:
null_vector=np.zeros(10,dtype=int)
null_vector[4]=1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [49]:
ranging=np.arange(10,50)
ranging

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [50]:
ranging[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [51]:
rangee=np.arange(0,9).reshape(3,3)
rangee

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr) # 🔴
indices

(array([0, 1, 4]),)

In [53]:
arr=np.identity(3,dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
arr=np.random.random((3,3,3))
arr

array([[[0.61440732, 0.99632775, 0.13066902],
        [0.72631861, 0.29784308, 0.10812569],
        [0.53145485, 0.08141491, 0.24666625]],

       [[0.29339351, 0.83228501, 0.19050619],
        [0.9000248 , 0.58707966, 0.78343488],
        [0.32146473, 0.47249126, 0.89147666]],

       [[0.67934324, 0.29137739, 0.09103217],
        [0.61471242, 0.99015384, 0.24132029],
        [0.13601227, 0.94534555, 0.77380677]]])

In [55]:
arr=np.random.random((10,10))
mx=arr.max()
mini=arr.min()
# print(arr)
print(mx)
print(mini)

0.9981187382643696
0.02304483857729156


In [56]:
arr=np.random.random(30)
average=arr.mean()
average

np.float64(0.4772925330933312)

In [57]:
Z=np.ones((5,5),dtype=int)
Z[1:-1,1:-1]=0 # Equal Z[1:4,1:4]=0
Z

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [58]:
arr=np.ones((3,3),dtype=int)
padded_arr=np.pad(arr, pad_width=1,mode='constant',constant_values=0) # 🔴
padded_arr

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [59]:
# 0 * np.nan # Equal nan
# np.nan == np.nan # np.nan=!np.nan = False
# np.inf > np.nan # np.inf < np.nan = False
# np.nan - np.nan # Equal nan
# np.nan in set([np.nan]) # Equal True
# 0.3 == 3 * 0.1 # Equal False # 🔴

In [60]:
matrix=np.diag([1,2,3,4],k=-1) # 🔴
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [61]:
z=np.zeros((8,8),dtype=int)
z[0::2,1::2]=1
z[1::2,0::2]=1 # 🔴
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [62]:
x=np.array((6,7,8),dtype=int)
print(np.unravel_index(99,x)) #🔴

(np.int64(1), np.int64(5), np.int64(3))


In [63]:
base_tile=np.array([[0,1],[1,0]])
checkboard=np.tile(base_tile,(4,4))
checkboard #🔴

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [64]:
z=np.random.randint(1,100,(5,5))
mini=z.min()
mx=z.max()
z_norm=(z-mini)/(mx-mini)
z_norm #🔴

array([[0.89010989, 0.9010989 , 0.32967033, 0.35164835, 0.49450549],
       [1.        , 0.53846154, 0.9010989 , 0.24175824, 0.14285714],
       [0.01098901, 0.        , 0.04395604, 0.63736264, 0.89010989],
       [0.02197802, 0.07692308, 0.8021978 , 0.02197802, 0.57142857],
       [0.94505495, 0.8021978 , 0.71428571, 0.04395604, 0.51648352]])

In [65]:
color_dtype=np.dtype([('r',np.ubyte,),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])
color_arr=np.array([(255, 0, 0, 255), (0, 255, 128, 120)],dtype=color_dtype)
print(f"The dtype of the matrix {color_dtype}")
print(f"The whole matrix is: {color_arr}")
print(f"Red color value is: {color_arr['r']}") #🔴


The dtype of the matrix [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
The whole matrix is: [(255,   0,   0, 255) (  0, 255, 128, 120)]
Red color value is: [255   0]


In [66]:
arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
print(f"Real matrix product Equal:{arr1@arr2}")

Real matrix product Equal:[[1.33610092 1.04143619]
 [1.47701208 1.28959469]
 [0.79015113 0.67816431]
 [1.49457347 1.14859403]
 [1.11024236 0.96228823]]


In [67]:
z=np.arange(11)
z[(z>3)&(z<8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [68]:
print(sum(range(5),-1)) # -> 10-1=9
from numpy import *
print(sum(range(5),-1)) # -> 10 🔴


10
10


In [71]:
#Z**Z # Legal 
#2 << Z >> 2 # Legal
#Z <- Z # Legal
#1j*Z # Legal 
#Z/1/1 # Legal
# Z<Z>Z # Ilegal

In [ ]:
Z = np.array([2.1, 2.9, -2.1, -2.9, 0.0])
print("Z:",Z)
rounded_z=np.copysign(np.ceil(np.abs(Z)),Z)
print("Rounded Z:",rounded_z) #🔴


Z: [ 2.1  2.9 -2.1 -2.9  0. ]
Rounded Z: [ 3.  3. -3. -3.  0.]


In [ ]:
Z1 = np.array([1, 2, 3, 4, 5])
Z2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(Z1,Z2)) #🔴

[3 4 5]


In [ ]:
"""
np.seterr(all='ignore') #🔴
Z = np.ones(1) / 0
print(Z) # OR
with np.errstate(all='ignore'):#🔴
    np.arange(3) / 0
""" 

"\nnp.seterr(all='ignore')\nZ = np.ones(1) / 0\nprint(Z) # OR\nwith np.errstate(all='ignore'):\n    np.arange(3) / 0\n"

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) # nan!=1j

In [ ]:
today=np.datetime64('today',"D") #🔴
yestrday=today-np.timedelta64(1,"D") #🔴
Tomorrow=today+np.timedelta64(1,"D")
print(f"Today is {today}")
print(f"Yesterday was {yestrday}")
print(f"Tomorrow wil be {Tomorrow}")

Today is 2026-07-19
Yesterday was 2026-07-18
Tomorrow wil be 2026-07-20


In [ ]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [ ]:
A = np.ones(3, dtype=float) * 2  # [2., 2., 2.]
B = np.ones(3, dtype=float) * 4  # [4., 4., 4.]
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)
print(f"The final result for A: {A}")

The final result for A: [-6. -6. -6.]


In [ ]:
arr=np.random.uniform(0,10,5)
method1=np.floor(arr) #🔴
method2=np.trunc(arr) #🔴
method3=arr.astype(int)
method4=arr-arr%2 🔴
print(f"The first method equal: {method1}")
print(f"The second method equal: {method2}")
print(f"The third method equal: {method3}")
print(f"The last method equal: {method4}")

The first method equal: [7. 0. 6. 4. 8.]
The first method equal: [7. 0. 6. 4. 8.]
The first method equal: [7 0 6 4 8]
The first method equal: [6. 0. 6. 4. 8.]


In [ ]:
# The First Way
Z=np.zeros((5,1),dtype=int)+np.arange(5) # <--------------
print(Z)
print("-"*20)
# The Second Way
row=np.arange(5)
x=np.tile(row,(5,1))#🔴 # <-------------
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
--------------------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
def genrate_integers():
    for x in range(10):
        yield x
iterable=genrate_integers()
Z=np.fromiter(iterable,dtype=int) #🔴
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z=np.linspace(0,1,12)[1:-1] #🔴
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
z=np.random.random(10)
print(z)
z.sort()
print(z)

[0.35182913 0.37126593 0.98398651 0.43694815 0.39729623 0.305186
 0.94847954 0.18336137 0.56829811 0.66341458]
[0.18336137 0.305186   0.35182913 0.37126593 0.39729623 0.43694815
 0.56829811 0.66341458 0.94847954 0.98398651]


In [ ]:
Z=np.arange(10)
total=sum(Z)
total

np.int64(45)

In [ ]:
A = np.array([1.0, 2.0])
B = np.array([1.0000000001, 2.0]) 
equal=np.array_equal(A,B) #🔴
print(equal)
equal_loose=np.allclose(A,B) #🔴
print(equal_loose)


False
True


In [ ]:
Z=np.arange(11)
Z.flags.writeable=False #🔴
Z
Z[0]=1

In [ ]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X) #🔴
print("R ----->",R)
print("T ----->",T)

R -----> [0.92514452 0.97406243 0.82757715 0.39240296 0.61762869 1.07239155
 0.58738123 1.29266506 0.50037996 0.89715083]
T -----> [0.51912691 1.35204511 1.46827272 1.17018443 0.65899716 0.63116505
 0.09501883 0.81352735 1.28860593 1.10294441]


In [ ]:
Z=np.random.random(10)
Z[Z.argmax()]=0 #🔴
Z

array([0.09744645, 0.        , 0.14484836, 0.64097169, 0.33203109,
       0.66503791, 0.60891089, 0.13791309, 0.79327425, 0.81553898])

In [ ]:
n=5
x_vals=np.linspace(0,1,n)
y_vals=np.linspace(0,1,n)
Z=np.zeros((n,n),dtype=[('x',float),('y',float)])
X,Y=np.meshgrid(x_vals,y_vals) #🔴
Z['x']=x
Z['y']=Y
Z

array([[(0., 0.  ), (1., 0.  ), (2., 0.  ), (3., 0.  ), (4., 0.  )],
       [(0., 0.25), (1., 0.25), (2., 0.25), (3., 0.25), (4., 0.25)],
       [(0., 0.5 ), (1., 0.5 ), (2., 0.5 ), (3., 0.5 ), (4., 0.5 )],
       [(0., 0.75), (1., 0.75), (2., 0.75), (3., 0.75), (4., 0.75)],
       [(0., 1.  ), (1., 1.  ), (2., 1.  ), (3., 1.  ), (4., 1.  )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
X = np.array([1, 2, 3, 4, 5])
Y = np.array([0.5, 1.5, 2.5, 3.5, 4.5])
denominator=np.subtract.outer(X,Y) #🔴
C=1/denominator
C

array([[ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ]])

In [ ]:
int_types=[np.int8,np.int16,np.int32,np.int64]
print("----Integers-----")
for dtype in int_types:
    info=np.iinfo(dtype) #🔴
    print(f"{dtype.__name__:<8} -> The Least: {info.min:<20} | The Max: {info.max}")
print("----Floating Points----")
float_types = [np.float16, np.float32, np.float64]
for dtype in float_types:
    info = np.finfo(dtype) #🔴
    print(f"{dtype.__name__:<8} -> The Least: {info.min:<20} | The Max: {info.max}")

----Integers-----
int8     -> The Least: -128                 | The Max: 127
int16    -> The Least: -32768               | The Max: 32767
int32    -> The Least: -2147483648          | The Max: 2147483647
int64    -> The Least: -9223372036854775808 | The Max: 9223372036854775807
----Floating Points----
float16  -> The Least: -65504.0             | The Max: 65504.0
float32  -> The Least: -3.4028234663852886e+38 | The Max: 3.4028234663852886e+38
float64  -> The Least: -1.7976931348623157e+308 | The Max: 1.7976931348623157e+308


In [ ]:
np.set_printoptions(threshold=np.inf) #🔴
Z=np.arange(2001)
Z

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1

In [ ]:
Z=np.random.uniform(0,100,10)
target=50
idx=np.abs(Z-target).argmin() #🔴
idx

np.int64(6)

In [ ]:
my_dtype = [
    ('position', [('x', 'f4'), ('y', 'f4')]),  
    ('color',    [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])]
structured_arr=np.zeros(3,dtype=my_dtype) #🔴
structured_arr[0]['position']=(10.5,20.3)
structured_arr[0]['color'] = (255, 0, 0)
print(structured_arr)

[((10.5, 20.3), (255, 0, 0)) (( 0. ,  0. ), (  0, 0, 0))
 (( 0. ,  0. ), (  0, 0, 0))]


In [ ]:
from scipy.spatial.distance import cdist
Z=np.random.random((100,2))
D=cdist(Z,Z)# 🔴
print(D.shape)

(100, 100)


In [ ]:
arr = np.array([1.2, 2.8, 3.9], dtype=np.float32)
print(f"Before Transform: {arr},{arr.dtype} ")
arr=arr.astype(np.int32,copy=False)
print(f" After Transform: {arr},{arr.dtype}")

Before Transform: [1.2 2.8 3.9],float32 
 After Transform: [1 2 3],int32


In [ ]:
import io
file_data = """1, 2, 3, 4, 5
6,  ,  , 7, 8
,  , 9,10,11"""
data=np.genfromtxt(io.StringIO(file_data),delimiter=",",filling_values="NaN") #🔴
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [ ]:
arr = np.array([[10, 20, 30], 
                [40, 50, 60]])
for index,value in np.ndenumerate(arr): #🔴
    print(f"Index:{index}, Value ---> {value}")

Index:(0, 0), Value ---> 10
Index:(0, 1), Value ---> 20
Index:(0, 2), Value ---> 30
Index:(1, 0), Value ---> 40
Index:(1, 1), Value ---> 50
Index:(1, 2), Value ---> 60


In [ ]:
size=10
X,Y=np.meshgrid(np.linspace(-1,1,size),np.linspace(-1,1,size))
D=np.sqrt(X**2+Y**2)
sigma,mu=1.0,0.0
D=G = np.exp(-((D - mu)**2 / (2.0 * sigma**2))) #🔴
print(f"Gaussian matrix --->{D}")

Gaussian matrix --->[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.734

In [ ]:
n=10
p=5
Z=np.zeros((10,10))
np.put(Z,np.random.choice(range(n*n),p,replace=False),50505) #🔴
Z

array([[    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0., 50505., 50505.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0., 50505.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0., 50505.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0., 50505.,
            0.,     0.]])

In [80]:
X=np.random.rand(5,3)
X_mean=X.mean(axis=0,keepdims=True)
X_subs=X-X_mean
print(f"The original X ---> {X}")
print(f"X After substract ---> {X_subs}")

The original X ---> [[0.30092816 0.15542288 0.13317917]
 [0.66067276 0.20152629 0.46864463]
 [0.84407197 0.40289878 0.37744624]
 [0.02462303 0.58573346 0.62006221]
 [0.24841978 0.09526923 0.18290652]]
X After substract ---> [[-0.11481498 -0.13274725 -0.22326858]
 [ 0.24492962 -0.08664384  0.11219687]
 [ 0.42832883  0.11472865  0.02099849]
 [-0.39112011  0.29756333  0.26361446]
 [-0.16732336 -0.19290089 -0.17354123]]


In [81]:
Z=np.random.randint(0,10,(5,3))
n=1
sorted_indices=Z[:,n].argsort()
Z_sorted=Z[sorted_indices]
print(f"Original Z ---> {Z} ")
print(f"Z After Sorting ---> {Z_sorted}")

Original Z ---> [[1 9 8]
 [6 3 1]
 [2 1 2]
 [6 8 8]
 [2 1 1]] 
Z After Sorting ---> [[2 1 2]
 [2 1 1]
 [6 3 1]
 [6 8 8]
 [1 9 8]]


In [88]:
Z = np.random.randint(0, 3, (5, 5))
Z[:, 1] = 0
null_columns=~Z.any(axis=0)
has_null_columns=null_columns.any()
print(F"Are there null columns in Z ? ---> {has_null_columns}")
print(F"Numbers of null columns ---> {null_columns}")

Are there null columns in Z ? ---> True
Numbers of null columns ---> [False  True False False False]


In [93]:
Z=np.random.uniform(0,10,10)
target=5.5
index=np.abs(Z-target).argmin()
nearest_value=Z[index]
print(Z)
print(target)
print(index)
print(nearest_value)

[0.08193235 1.4639027  3.30225899 7.54905515 2.13074675 3.39253057
 1.4443569  2.3350922  6.07203271 6.97020737]
5.5
8
6.072032706720658


In [ ]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None],flags=['buffered','multi_index'],op_flags=[['readonly'],['readonly'],['writeonly','allocate']]) #🔴🔴
for x,y,res in it:
    res[...]=x+y
print(f'The result after sum by iterator {it.operands[2]}') #🔴

The result after sum by iterator [[0 1 2]
 [1 2 3]
 [2 3 4]]
