In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [100]:
#print("Numpy version:",np.__version__)
#print(f"Numpy Configuration: {np.show_config()}")

In [4]:
Null_vector=np.zeros(10,dtype=int)
Null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr=np.array([1,2,3,4])
print(arr.nbytes) # Equal arr.itemsize * arr.sizec

32


In [6]:
# Bash: python -m pydoc numpy.add This in cmd for documentation

In [7]:
null_vector=np.zeros(10,dtype=int)
null_vector[4]=1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [8]:
ranging=np.arange(10,50)
ranging

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
ranging[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
rangee=np.arange(0,9).reshape(3,3)
rangee

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr) # 🔴
indices

(array([0, 1, 4]),)

In [12]:
arr=np.identity(3,dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
arr=np.random.random((3,3,3))
arr

array([[[0.79546674, 0.57370419, 0.66902823],
        [0.53440861, 0.60949086, 0.4774718 ],
        [0.33437313, 0.66182028, 0.56958251]],

       [[0.85054041, 0.92435825, 0.47196349],
        [0.27366738, 0.87456408, 0.72483804],
        [0.87857736, 0.28093868, 0.20204818]],

       [[0.62777322, 0.26350109, 0.16423518],
        [0.78559358, 0.60017544, 0.65548607],
        [0.73845989, 0.73742522, 0.45046812]]])

In [14]:
arr=np.random.random((10,10))
mx=arr.max()
mini=arr.min()
# print(arr)
print(mx)
print(mini)

0.9995102640831637
0.032108952081138065


In [15]:
arr=np.random.random(30)
average=arr.mean()
average

np.float64(0.4677935894762608)

In [16]:
Z=np.ones((5,5),dtype=int)
Z[1:-1,1:-1]=0 # Equal Z[1:4,1:4]=0
Z

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [17]:
arr=np.ones((3,3),dtype=int)
padded_arr=np.pad(arr, pad_width=1,mode='constant',constant_values=0) # 🔴
padded_arr

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [18]:
# 0 * np.nan # Equal nan
# np.nan == np.nan # np.nan=!np.nan = False
# np.inf > np.nan # np.inf < np.nan = False
# np.nan - np.nan # Equal nan
# np.nan in set([np.nan]) # Equal True
# 0.3 == 3 * 0.1 # Equal False # 🔴

In [19]:
matrix=np.diag([1,2,3,4],k=-1) # 🔴
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [20]:
z=np.zeros((8,8),dtype=int)
z[0::2,1::2]=1
z[1::2,0::2]=1 # 🔴
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [21]:
x=np.array((6,7,8),dtype=int)
print(np.unravel_index(99,x)) #🔴

(np.int64(1), np.int64(5), np.int64(3))


In [22]:
base_tile=np.array([[0,1],[1,0]])
checkboard=np.tile(base_tile,(4,4))
checkboard #🔴

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
z=np.random.randint(1,100,(5,5))
mini=z.min()
mx=z.max()
z_norm=(z-mini)/(mx-mini)
z_norm #🔴

array([[0.10638298, 0.34042553, 0.79787234, 0.58510638, 0.57446809],
       [0.85106383, 0.78723404, 0.43617021, 0.89361702, 0.21276596],
       [0.24468085, 1.        , 0.30851064, 0.45744681, 0.80851064],
       [0.18085106, 0.82978723, 0.80851064, 0.41489362, 0.18085106],
       [0.0212766 , 0.69148936, 0.54255319, 0.86170213, 0.        ]])

In [24]:
color_dtype=np.dtype([('r',np.ubyte,),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])
color_arr=np.array([(255, 0, 0, 255), (0, 255, 128, 120)],dtype=color_dtype)
print(f"The dtype of the matrix {color_dtype}")
print(f"The whole matrix is: {color_arr}")
print(f"Red color value is: {color_arr['r']}") #🔴


The dtype of the matrix [('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
The whole matrix is: [(255,   0,   0, 255) (  0, 255, 128, 120)]
Red color value is: [255   0]


In [25]:
arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
print(f"Real matrix product Equal:{arr1@arr2}")

Real matrix product Equal:[[0.70575901 0.25420269]
 [0.73428757 0.62138206]
 [1.64504579 1.39557117]
 [1.35099506 0.73053039]
 [0.69463223 0.54362783]]


In [26]:
z=np.arange(11)
z[(z>3)&(z<8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [27]:
print(sum(range(5),-1)) # -> 10-1=9
from numpy import *
print(sum(range(5),-1)) # -> 10 🔴


9
10


In [28]:
#Z**Z # Legal 
#2 << Z >> 2 # Legal
#Z <- Z # Legal
#1j*Z # Legal 
#Z/1/1 # Legal
# Z<Z>Z # Ilegal

In [29]:
Z = np.array([2.1, 2.9, -2.1, -2.9, 0.0])
print("Z:",Z)
rounded_z=np.copysign(np.ceil(np.abs(Z)),Z)
print("Rounded Z:",rounded_z) #🔴


Z: [ 2.1  2.9 -2.1 -2.9  0. ]
Rounded Z: [ 3.  3. -3. -3.  0.]


In [30]:
Z1 = np.array([1, 2, 3, 4, 5])
Z2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(Z1,Z2)) #🔴

[3 4 5]


In [31]:
"""
np.seterr(all='ignore') #🔴
Z = np.ones(1) / 0
print(Z) # OR
with np.errstate(all='ignore'):#🔴
    np.arange(3) / 0
""" 

"\nnp.seterr(all='ignore') #🔴\nZ = np.ones(1) / 0\nprint(Z) # OR\nwith np.errstate(all='ignore'):#🔴\n    np.arange(3) / 0\n"

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1) # nan!=1j

np.False_

In [33]:
today=np.datetime64('today',"D") #🔴
yestrday=today-np.timedelta64(1,"D") #🔴
Tomorrow=today+np.timedelta64(1,"D")
print(f"Today is {today}")
print(f"Yesterday was {yestrday}")
print(f"Tomorrow wil be {Tomorrow}")

Today is 2026-07-22
Yesterday was 2026-07-21
Tomorrow wil be 2026-07-23


In [34]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [35]:
A = np.ones(3, dtype=float) * 2  # [2., 2., 2.]
B = np.ones(3, dtype=float) * 4  # [4., 4., 4.]
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)
print(f"The final result for A: {A}")

The final result for A: [-6. -6. -6.]


In [36]:
arr=np.random.uniform(0,10,5)
method1=np.floor(arr) #🔴
method2=np.trunc(arr) #🔴
method3=arr.astype(int)
method4=arr-arr%2 #🔴
print(f"The first method equal: {method1}")
print(f"The second method equal: {method2}")
print(f"The third method equal: {method3}")
print(f"The last method equal: {method4}")

The first method equal: [3. 0. 9. 8. 2.]
The second method equal: [3. 0. 9. 8. 2.]
The third method equal: [3 0 9 8 2]
The last method equal: [2. 0. 8. 8. 2.]


In [37]:
# The First Way
Z=np.zeros((5,1),dtype=int)+np.arange(5) # <--------------
print(Z)
print("-"*20)
# The Second Way
row=np.arange(5)
x=np.tile(row,(5,1))#🔴 # <-------------
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
--------------------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [38]:
def genrate_integers():
    for x in range(10):
        yield x
iterable=genrate_integers()
Z=np.fromiter(iterable,dtype=int) #🔴
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
z=np.linspace(0,1,12)[1:-1] #🔴
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [40]:
z=np.random.random(10)
print(z)
z.sort()
print(z)

[0.51359745 0.85743355 0.86983992 0.31372192 0.4773551  0.96723896
 0.77491435 0.18860424 0.69590531 0.28011967]
[0.18860424 0.28011967 0.31372192 0.4773551  0.51359745 0.69590531
 0.77491435 0.85743355 0.86983992 0.96723896]


In [41]:
Z=np.arange(10)
total=sum(Z)
total

np.int64(45)

In [42]:
A = np.array([1.0, 2.0])
B = np.array([1.0000000001, 2.0]) 
equal=np.array_equal(A,B) #🔴
print(equal)
equal_loose=np.allclose(A,B) #🔴
print(equal_loose)


False
True


In [43]:
Z=np.arange(11)
Z.flags.writeable=False #🔴
Z
#Z[0]=1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X) #🔴
print("R ----->",R)
print("T ----->",T)

R -----> [0.63337099 0.55751056 0.44275476 0.53781475 0.88991428 1.00522518
 0.80197459 0.1534552  0.70881595 1.03932857]
T -----> [0.87173213 0.60160623 0.49955572 0.62049707 1.22207422 1.16808136
 0.31153499 0.47044583 0.82560809 0.53411885]


In [45]:
Z=np.random.random(10)
Z[Z.argmax()]=0 #🔴
Z

array([0.66323796, 0.69606626, 0.39461649, 0.        , 0.00621339,
       0.17953441, 0.73899232, 0.10240696, 0.39722973, 0.74811668])

In [46]:
n=5
x_vals=np.linspace(0,1,n)
y_vals=np.linspace(0,1,n)
Z=np.zeros((n,n),dtype=[('x',float),('y',float)])
X,Y=np.meshgrid(x_vals,y_vals) #🔴
Z['x']=x
Z['y']=Y
Z

array([[(0., 0.  ), (1., 0.  ), (2., 0.  ), (3., 0.  ), (4., 0.  )],
       [(0., 0.25), (1., 0.25), (2., 0.25), (3., 0.25), (4., 0.25)],
       [(0., 0.5 ), (1., 0.5 ), (2., 0.5 ), (3., 0.5 ), (4., 0.5 )],
       [(0., 0.75), (1., 0.75), (2., 0.75), (3., 0.75), (4., 0.75)],
       [(0., 1.  ), (1., 1.  ), (2., 1.  ), (3., 1.  ), (4., 1.  )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [47]:
X = np.array([1, 2, 3, 4, 5])
Y = np.array([0.5, 1.5, 2.5, 3.5, 4.5])
denominator=np.subtract.outer(X,Y) #🔴
C=1/denominator
C

array([[ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ]])

In [48]:
int_types=[np.int8,np.int16,np.int32,np.int64]
print("----Integers-----")
for dtype in int_types:
    info=np.iinfo(dtype) #🔴
    print(f"{dtype.__name__:<8} -> The Least: {info.min:<20} | The Max: {info.max}")
print("----Floating Points----")
float_types = [np.float16, np.float32, np.float64]
for dtype in float_types:
    info = np.finfo(dtype) #🔴
    print(f"{dtype.__name__:<8} -> The Least: {info.min:<20} | The Max: {info.max}")

----Integers-----
int8     -> The Least: -128                 | The Max: 127
int16    -> The Least: -32768               | The Max: 32767
int32    -> The Least: -2147483648          | The Max: 2147483647
int64    -> The Least: -9223372036854775808 | The Max: 9223372036854775807
----Floating Points----
float16  -> The Least: -65504.0             | The Max: 65504.0
float32  -> The Least: -3.4028234663852886e+38 | The Max: 3.4028234663852886e+38
float64  -> The Least: -1.7976931348623157e+308 | The Max: 1.7976931348623157e+308


In [49]:
np.set_printoptions(threshold=np.inf) #🔴
Z=np.arange(2001)
Z

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1

In [50]:
Z=np.random.uniform(0,100,10)
target=50
idx=np.abs(Z-target).argmin() #🔴
idx

np.int64(5)

In [51]:
my_dtype = [
    ('position', [('x', 'f4'), ('y', 'f4')]),  
    ('color',    [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])]
structured_arr=np.zeros(3,dtype=my_dtype) #🔴
structured_arr[0]['position']=(10.5,20.3)
structured_arr[0]['color'] = (255, 0, 0)
print(structured_arr)

[((10.5, 20.3), (255, 0, 0)) (( 0. ,  0. ), (  0, 0, 0))
 (( 0. ,  0. ), (  0, 0, 0))]


In [52]:
from scipy.spatial.distance import cdist
Z=np.random.random((100,2))
D=cdist(Z,Z)# 🔴
print(D.shape)

(100, 100)


In [53]:
arr = np.array([1.2, 2.8, 3.9], dtype=np.float32)
print(f"Before Transform: {arr},{arr.dtype} ")
arr=arr.astype(np.int32,copy=False)
print(f" After Transform: {arr},{arr.dtype}")

Before Transform: [1.2 2.8 3.9],float32 
 After Transform: [1 2 3],int32


In [54]:
import io
file_data = """1, 2, 3, 4, 5
6,  ,  , 7, 8
,  , 9,10,11"""
data=np.genfromtxt(io.StringIO(file_data),delimiter=",",filling_values="NaN") #🔴
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [55]:
arr = np.array([[10, 20, 30], 
                [40, 50, 60]])
for index,value in np.ndenumerate(arr): #🔴
    print(f"Index:{index}, Value ---> {value}")

Index:(0, 0), Value ---> 10
Index:(0, 1), Value ---> 20
Index:(0, 2), Value ---> 30
Index:(1, 0), Value ---> 40
Index:(1, 1), Value ---> 50
Index:(1, 2), Value ---> 60


In [56]:
size=10
X,Y=np.meshgrid(np.linspace(-1,1,size),np.linspace(-1,1,size))
D=np.sqrt(X**2+Y**2)
sigma,mu=1.0,0.0
D=G = np.exp(-((D - mu)**2 / (2.0 * sigma**2))) #🔴
print(f"Gaussian matrix --->{D}")

Gaussian matrix --->[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.734

In [57]:
n=10
p=5
Z=np.zeros((10,10))
np.put(Z,np.random.choice(range(n*n),p,replace=False),50505) #🔴
Z

array([[    0.,     0., 50505.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0., 50505.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0., 50505.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0., 50505.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [50505.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.]])

In [58]:
X=np.random.rand(5,3)
X_mean=X.mean(axis=0,keepdims=True)
X_subs=X-X_mean
print(f"The original X ---> {X}")
print(f"X After substract ---> {X_subs}")

The original X ---> [[0.48704887 0.02214242 0.21461707]
 [0.50374347 0.37006708 0.45630866]
 [0.56933947 0.13037321 0.315475  ]
 [0.61050844 0.79681861 0.12016401]
 [0.7811849  0.35013371 0.29937333]]
X After substract ---> [[-0.10331616 -0.31176459 -0.06657054]
 [-0.08662156  0.03616008  0.17512104]
 [-0.02102556 -0.2035338   0.03428739]
 [ 0.02014341  0.4629116  -0.1610236 ]
 [ 0.19081987  0.0162267   0.01818572]]


In [59]:
Z=np.random.randint(0,10,(5,3))
n=1
sorted_indices=Z[:,n].argsort()
Z_sorted=Z[sorted_indices]
print(f"Original Z ---> {Z} ")
print(f"Z After Sorting ---> {Z_sorted}")

Original Z ---> [[7 9 1]
 [8 5 5]
 [1 2 5]
 [8 8 7]
 [8 4 2]] 
Z After Sorting ---> [[1 2 5]
 [8 4 2]
 [8 5 5]
 [8 8 7]
 [7 9 1]]


In [60]:
Z = np.random.randint(0, 3, (5, 5))
Z[:, 1] = 0
null_columns=~Z.any(axis=0)
has_null_columns=null_columns.any()
print(F"Are there null columns in Z ? ---> {has_null_columns}")
print(F"Numbers of null columns ---> {null_columns}")

Are there null columns in Z ? ---> True
Numbers of null columns ---> [False  True False False False]


In [61]:
Z=np.random.uniform(0,10,10)
target=5.5
index=np.abs(Z-target).argmin()
nearest_value=Z[index]
print(Z)
print(target)
print(index)
print(nearest_value)

[5.96310761 9.10994886 5.18495416 9.85158848 1.49309108 3.79718367
 9.35189884 1.82010462 5.14263211 7.40063098]
5.5
2
5.184954164677322


In [62]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None],flags=['buffered','multi_index'],op_flags=[['readonly'],['readonly'],['writeonly','allocate']]) #🔴🔴
for x,y,res in it:
    res[...]=x+y
print(f'The result after sum by iterator {it.operands[2]}') #🔴

The result after sum by iterator [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [63]:
class NamedArray(np.ndarray): #🔴
    def __new__(cls, array, name='Default'):
        obj=np.asarray(array).view(cls)
        obj.name=name
        return obj
    def __array_finalize__(self, obj): #🔴
        if obj is None: return
        self.name=getattr(obj,'name','Default')
Z=NamedArray(np.arange(11),name='My_array')
print(F"Name of the array: {Z.name}")
print(F"The matrix: {Z}")
new_Z=Z*2
print(F"Name of the matrix after multiplication: {new_Z.name}")
print(F"Matrix after multiplication: {new_Z}")

Name of the array: My_array
The matrix: [ 0  1  2  3  4  5  6  7  8  9 10]
Name of the matrix after multiplication: My_array
Matrix after multiplication: [ 0  2  4  6  8 10 12 14 16 18 20]


In [64]:
Z=np.zeros(10)
I=np.array([1,1,3,4,3,3])
np.add.at(Z,I,1) #🔴
print(f"Vector after editing: {Z}")

Vector after editing: [0. 2. 0. 3. 1. 0. 0. 0. 0. 0.]


In [65]:
A=np.array([10,20,30,40,50,60])
B=np.array([1,5,1,3,4,3])
K=np.zeros(6)
np.add.at(K,B,A)
print(f"The last result---> {K}")

The last result---> [  0.  40.   0. 100.  50.  20.]


In [66]:
w,h=100,100
image=np.random.randint(0,256,(w,h,3),dtype=ubyte)
pixels=image.reshape( -1, 3)
unique_colors=np.unique(pixels,axis=0) #🔴
print(f"Number of unique colors ---> {len(unique_colors)}")

Number of unique colors ---> 9997

In [67]:
Z=np.random.randint(0,10,(2,3,4,5))
result=Z.sum(axis=(-2,-1)) #🔴
print(f"The original shape of the matrix---> {Z.shape}")
print(f"Shape of the matrix after editing---> {result.shape}")

The original shape of the matrix---> (2, 3, 4, 5)
Shape of the matrix after editing---> (2, 3)


In [68]:
D = np.array([10, 20, 30, 40, 50, 60])
S = np.array([0, 1, 0, 1, 2, 1])
sums=np.zeros(3)
np.add.at(sums,S,D)
counts=np.zeros(3)
np.add.at(counts,S,1)
mean=sums/counts
print(f"Sum of all numbers---> {sums}")
print(f"count of numbers---> {counts}")
print(f"Mean of the matrix---> {mean}")

Sum of all numbers---> [ 40. 120.  50.]
count of numbers---> [2. 3. 1.]
Mean of the matrix---> [20. 40. 50.]


In [69]:
A = np.random.randint(0, 10, (5, 5))
B = np.random.randint(0, 10, (5, 5))
diagonal=np.einsum("ij,ji->i",A,B) #🔴
print(f"Result of the diagonal---> {diagonal}")

Result of the diagonal---> [ 70  49 206 131  51]


In [70]:
M=np.array([1,2,3,4,5])
nz=3
M0=np.zeros(len(M)+(len(M)-1)*nz)
M0[::nz+1]=M
print(M)
print(M0)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [71]:
A=np.random.randint(0,10,(5,5,3))
B=np.random.randint(0,10,(5,5))
res=A*B[:,:,np.newaxis] #🔴
print(res.shape)

(5, 5, 3)


In [72]:
A=np.arange(9).reshape(3,3)
print(f"A Before edit anything---> {A}")
A[[0,1]]=A[[1,0]]
print(f"A after edit---> {A}")

A Before edit anything---> [[0 1 2]
 [3 4 5]
 [6 7 8]]
A after edit---> [[3 4 5]
 [0 1 2]
 [6 7 8]]


In [73]:
faces=np.random.randint(0,100,(10,3))
F=np.roll(faces.repeat(2,axis=1),-1,axis=1) #🔴
F=F.reshape(len(F)*3,2)
F.sort(axis=1)
unique_edges=np.unique(F,axis=1)
print(unique_edges)

[[65 81]
 [65 66]
 [66 81]
 [32 72]
 [72 73]
 [32 73]
 [10 33]
 [10 14]
 [14 33]
 [45 52]
 [37 45]
 [37 52]
 [56 72]
 [54 56]
 [54 72]
 [54 58]
 [54 99]
 [58 99]
 [19 80]
 [28 80]
 [19 28]
 [11 48]
 [13 48]
 [11 13]
 [54 67]
 [42 67]
 [42 54]
 [34 58]
 [12 58]
 [12 34]]


In [74]:
C=np.array([1,2,3,4,5])
A=np.repeat(np.arange(len(C)),C)
print(A)

[0 1 1 2 2 2 3 3 3 3 4 4 4 4 4]


In [75]:
arr=np.array([10,20,30,40,50])
window=3
weights=np.ones(window)/window
result=np.convolve(arr,weights,mode='valid') #🔴
print(result)

[20. 30. 40.]


In [76]:
from numpy.lib.stride_tricks import as_strided
Z=np.array([1,2,3,4,5])
window_size=3
rows=len(Z)-window_size+1
cols=window_size
shape=(rows,cols)
strides = (Z.strides[0], Z.strides[0])
result=as_strided(Z,shape=shape,strides=strides)
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [77]:
Z_bool=np.array([True,False,True])
np.logical_not(Z_bool,out=Z_bool)
print(f"Z_bool after editing---> {Z_bool}")
"---------------------------------------"
Z_float=np.array([1.2,-2.8,-3.4,9.7])
np.negative(Z_float,out=Z_float)
print(f'Z_float after editing---> {Z_float}')

Z_bool after editing---> [False  True False]
Z_float after editing---> [-1.2  2.8  3.4 -9.7]


In [78]:
# The law= |p1-p0|*|p-p0| / |p1-p0| 
# Equal cross_product/ line_length=Parallelogram_area/Base_length=distance
p = np.array([2.0, 1.0])

P0 = np.array([[0.0, 0.0], [1.0, 2.0], [0.0, 1.0]])

P1 = np.array([[4.0, 0.0], [4.0, 2.0], [3.0, 5.0]])
vec_line=P1-P0
vec_p=p-P0
cross_prod=np.abs(vec_line[:,0]*vec_p[:,1]-vec_line[:,1]*vec_p[:,0]) #🔴
line_len=np.linalg.norm(vec_line,axis=1) #🔴
distances=cross_prod/line_len
print(f"Distance from the point for every line---> {distances}")

Distance from the point for every line---> [1.  1.  1.6]


In [79]:
P0 = np.array([[0.0, 0.0], [1.0, 1.0]])  
P1 = np.array([[4.0, 0.0], [4.0, 3.0]])  

P = np.array([[2.0, 1.0], [0.0, 2.0], [3.0, 3.0]])
P0_bro=P0[np.newaxis,:,:] #shape: (1,N_lines,2)
P1_bro = P1[np.newaxis, :, :]  #shape: (1, N_lines, 2)
P_bro  = P[ :, np.newaxis, :]  #shape: (M_points, 1, 2)
vec_line = P1_bro - P0_bro          
vec_p = P0_bro - P_bro
cross_prod = np.abs(vec_line[:, :, 0] * vec_p[:, :, 1] - vec_line[:, :, 1] * vec_p[:, :, 0])

line_length = np.linalg.norm(vec_line, axis=2) 
distance=cross_prod/line_length
print(distance)

[[1.         0.5547002 ]
 [2.         1.38675049]
 [3.         0.5547002 ]]


In [80]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size=4
shape=(len(Z)-window_size+1,window_size)
strides=(Z.strides[0],Z.strides[0])
R=np.lib.stride_tricks.as_strided(Z,shape=shape,strides=strides)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [81]:
Z = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
r=np.linalg.matrix_rank(Z)
r

np.int64(2)

In [82]:
Z = np.array([1, 2, 3, 2, 4, 2, 5, 1, 2, 3])
val,count=np.unique(Z,return_counts=True)
most_frequent=val[np.argmax(count)]
print(F"Most frequent number---> {most_frequent:.2f}")

Most frequent number---> 2.00


In [83]:
Z = np.random.randint(0, 10, (10, 10))
block_shape=(3,3)
shape=(Z.shape[0]-block_shape[0]+1,
    Z.shape[1]-block_shape[1]+1)+block_shape
strides=Z.strides*2
blocks=np.lib.stride_tricks.as_strided(Z,shape=shape,strides=strides)
print("Shape of extracted blocks:", blocks.shape)

Shape of extracted blocks: (8, 8, 3, 3)


In [84]:
class SymmetricArray(np.ndarray):
    def __setitem__(self,index,value):
        i,j=index
        super().__setitem__((i,j),value) #🔴
        super().__setitem__((j,i),value)
def symmetric_matrix(input_array):
    return np.asarray(input_array).view(SymmetricArray)
Z=symmetric_matrix(np.zeros((3,3)))
Z[0,1]=6
Z

SymmetricArray([[0., 6., 0.],
                [6., 0., 0.],
                [0., 0., 0.]])

In [85]:
p = 5 
n = 3
matrices=np.random.rand(p,n,n)
vectors=np.random.rand(p,n,1)
result=np.sum(np.matmul(matrices,vectors),axis=0) #🔴
print(result.shape)
print(result)

(3, 1)
[[3.2300327 ]
 [3.59016881]
 [4.31800985]]


In [86]:
Z = np.arange(256).reshape(16, 16)
block_size = 4
reshaped_Z=Z.reshape(16//block_size,block_size,16//block_size,block_size)
block_sum=reshaped_Z.sum(axis=(1,3))
print("Original shape:", Z.shape)
print("Block sum shape:", block_sum.shape)
print(block_sum)

Original shape: (16, 16)
Block sum shape: (4, 4)
[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


In [87]:
def game_of_life(grid, num_iterations=5):
    for _ in range(num_iterations):
        n = np.zeros_like(grid, dtype=int) #🔴
        for dr in [-1,0,1]:
            for dc in [-1,0,1]:
                if dr==0 and dc==0:
                    continue
                n+=np.roll(np.roll(grid,dr,axis=0),dc,axis=1)
        birth = (n == 3) & (grid == 0)
        survive = ((n == 2) | (n == 3)) & (grid == 1)
        grid = (birth | survive).astype(int)
    return grid
Z = np.random.randint(0, 2, (5, 5))
print(game_of_life(Z, 2))

[[0 0 1 1 1]
 [0 0 1 1 1]
 [0 1 1 1 1]
 [0 0 0 0 0]
 [0 0 1 0 0]]


In [88]:
Z = np.array([10, 5, 8, 20, 3, 15, 25, 1])
n = 3
largest_values=np.partition(Z,-n)[-n:] # largest_values = Z[np.argsort(Z)[-n:]] #🔴
print(f"Largest Values---> {largest_values}")

Largest Values---> [15 20 25]


In [89]:
def cartesian_product(vectors):
    grid=np.meshgrid(*vectors,indexing='ij')
    return np.stack(grid,axis=-1).reshape(-1,len(vectors)) #🔴
v1 = np.array([1, 2])
v2 = np.array([3, 4])
v3 = np.array([5])

result = cartesian_product([v1, v2, v3])
print(result)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]]


In [90]:
data = np.array([[25, 70.5, 95],
                [30, 65.0, 88],
                [22, 80.2, 92],
                [28, 75.0, 90]])
rec_arr=np.rec.fromarrays(data.T,names="name,weight,score",formats="i4,f4,i4") #🔴
print("Record Array:")
print(rec_arr)


Record Array:
[(25, 70.5, 95) (30, 65. , 88) (22, 80.2, 92) (28, 75. , 90)]


In [91]:
Z = np.random.rand(20)
res1=Z**3
res2=Z*Z*Z
res3=np.power(Z,3)
print("Are all methods equal?", np.allclose(res1, res2) and np.allclose(res2, res3))

Are all methods equal? True


In [92]:
np.random.seed(42)
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))

print("Array A:\n", A)
print("\nArray B:\n", B)
def check_row(row_a, B):
    for row_b in B:
        
        if np.all(np.isin(row_b, row_a)):
            return True
    return False


final_mask = np.array([check_row(row_a, B) for row_a in A])
result = A[final_mask]
res=A[final_mask]
print("\nResult rows from A:\n", result)

Array A:
 [[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]
 [7 2 5]
 [4 1 7]
 [5 1 4]
 [0 9 5]]

Array B:
 [[8 0]
 [9 2]]

Result rows from A:
 []


In [93]:
np.random.seed(42)
Z = np.random.randint(1, 4, (10, 3))
print("Original Matrix Z:\n", Z)
unequal_rows_mask=np.any(Z!=Z[:,0:1],axis=1)
res=Z[unequal_rows_mask]
print("\nRows with unequal values:\n", result)

Original Matrix Z:
 [[3 1 3]
 [3 1 1]
 [3 2 3]
 [3 3 3]
 [1 3 2]
 [1 2 2]
 [2 2 1]
 [1 2 2]
 [1 1 1]
 [3 3 3]]

Rows with unequal values:
 []


In [94]:
Z = np.array([0, 1, 2, 3, 4, 8], dtype=np.uint8)
binary_matrix=np.unpackbits(Z[:,np.newaxis].view(np.uint8),axis=1)
print("Original Integers:", Z) #🔴
print("\nBinary Representation Matrix:\n", binary_matrix)

Original Integers: [0 1 2 3 4 8]

Binary Representation Matrix:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]]


In [95]:
Z = np.array([[1, 2, 3],
            [4, 5, 6],
            [1, 2, 3],  
            [7, 8, 9],
            [4, 5, 6]]) 

print("Original Matrix:\n", Z)
unique_rows=np.unique(Z,axis=0)
print("\nUnique Rows:\n", unique_rows)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Unique Rows:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner_prod=np.einsum('i,i->',A,B)
print("1. Inner Product:", inner_prod)  # 1*4 + 2*5 + 3*6 = 32
outer_prod=np.einsum('i,j->ij',A,B)
print("\n2. Outer Product:\n", outer_prod)
sum_A=np.einsum('i->',A)
print("\n3. Sum of A:", sum_A)  # 1 + 2 + 3 = 6
mul_res=np.einsum('i,i->i',A,B)
print("\n4. Element-wise Multiplication:", mul_res)  # [4, 10, 18]

1. Inner Product: 32

2. Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

3. Sum of A: 6

4. Element-wise Multiplication: [ 4 10 18]


In [97]:
from scipy.interpolate import interp1d
X = np.array([0.0, 1.0, 2.5, 4.0, 7.0])
Y = np.array([0.0, 2.0, 1.0, 5.0, 3.0])
dx=np.diff(X)
dy=np.diff(Y)
segment_lengths = np.sqrt(dx**2 + dy**2)
distance=np.insert(np.cumsum(segment_lengths),0,0.0) #🔴🔴
total_length = distance[-1]
num_samples = 10
equal_distances = np.linspace(0, total_length, num_samples)
interp_x=interp1d(distance, X)
interp_y=interp1d(distance, Y)
new_X = interp_x(equal_distances)
new_Y = interp_y(equal_distances)
print("Original X:", X)
print("New Equidistant X:", new_X)
print("\nOriginal Y:", Y)
print("New Equidistant Y:", new_Y)

Original X: [0.  1.  2.5 4.  7. ]
New Equidistant X: [0.         0.59213052 1.34282152 2.44449279 2.94147899 3.40638191
 3.87128483 4.79665746 5.89832873 7.        ]

Original Y: [0. 2. 1. 5. 3.]
New Equidistant Y: [0.         1.18426103 1.77145232 1.0370048  2.17727732 3.41701842
 4.65675953 4.46889503 3.73444751 3.        ]


In [98]:
n = 10
X = np.array([[2, 3, 5],       
            [1.5, 4, 4.5],  
            [4, 4, 3],      
            [0, 10, 0],     
            [1, 2, 7]])
is_integer=(X==np.floor(X))
all_integers=np.all(is_integer,axis=1)
sum_to_n=(np.sum(X,axis=1)==n)
valid_rows_mask=all_integers & sum_to_n
result = X[valid_rows_mask]

print("Selected Multinomial Rows:\n", result)

Selected Multinomial Rows:
 [[ 2.  3.  5.]
 [ 0. 10.  0.]
 [ 1.  2.  7.]]


In [99]:
np.random.seed(42)
X = np.array([12, 15, 14, 10, 18, 20, 22, 19, 11, 16])
N=1000
n_samples=len(X)
resampled_indices=np.random.randint(0,n_samples,size=(N,n_samples))
resampled_arrays=X[resampled_indices]
bootstrap_means=np.mean(resampled_arrays,axis=1)
ci_lower, ci_upper = np.percentile(bootstrap_means, [2.5, 97.5])
print(f"Original Mean: {np.mean(X):.4f}")
print(f"Bootstrapped 95% Confidence Interval: [{ci_lower:.4f}, {ci_upper:.4f}]")
# StandWithPalestine 🍉

Original Mean: 15.7000
Bootstrapped 95% Confidence Interval: [13.4000, 17.9025]
